symbols = [
  "^ES[FGHJKMNQUVXZ][0-9]$"  # futures
]

[accounts]

  [accounts.A1]
  login = "M9H"
  password = "uaxIRXP9SuJZ02z7cVN1"
  secret = "6YPQyMHZH8_bVh_rJ6N250cNXy901j_zYnuVsKrFz00"
  symbols = ".*"

[users]

  [users.test]
  password = "1234"
  symbols = ".*"

  [users.trader]
  password = "secret"
  accounts = [ "A1" ]
  symbols = [ "BTC-\\d{2}\\D{3}\\d{2}" ]

[rate_limits]

  [rate_limits.global]
    type = "ORDER_ACTION"
    aggregate = true
    request_limit = 100
    monitor_period = "10s"
    ban_period = "5m"

  [rate_limits.A1]
    type = "CREATE_ORDER"
    accounts = "A.*"
    request_limit = 30
    monitor_period = "1s"
    ban_period = "5m"

  [rate_limits.market_maker]
    type = "CREATE_ORDER"
    users = [ "trader" ]
    request_limit = 20
    monitor_period = "200ms"
    ban_period = "5m"
