#!/usr/bin/env bash

if [[ -z $CONDA_PREFIX ]]; then
  (>&2 echo -e "\033[1;31mERROR: Please activate your conda environment before using this script.\033[0m") && exit 1
fi

if [[ -z $1 ]]; then
  (>&2 echo -e "\033[1;31mERROR: Expected second argument to be environment. Use one of 'prod', 'test' or 'cert'.\033[0m") && exit 1
fi

if [[ -z $2 ]]; then
  (>&2 echo -e "\033[1;31mERROR: Expected third argument to be comma-separated list of channel id's\033[0m") && exit 1
fi

ENV="$1"
CHANNEL_IDS="$2"

echo "ENV=$ENV"
echo "CHANNEL_IDS=$CHANNEL_IDS"

CONFIG_FILE="$CONDA_PREFIX/share/roq-cme/$ENV/config.xml"

echo "CONFIG_FILE=$CONFIG_FILE"

FILTER=$(roq-cme-pcap-filter --type tcpdump --config_file $CONFIG_FILE --channel_ids $CHANNEL_IDS)

echo "FILTER=$FILTER"

tcpdump $FILTER $@
